// src/views/Shop.vue
<template>
    <div class="shop-page">
        <b-row>
            <b-col md="2" sm="12">
                <h3>Filter By</h3>
                <div class="filter-item">
                    <h5 class="filter-title">Category</h5>
                    <v-select :options="options"></v-select>
                </div>
                <div class="filter-item">
                    <h5 class="filter-title">Author</h5>
                    <v-select :options="options"></v-select>
                </div>
                <div class="filter-item">
                    <h5 class="filter-title">Rating Review</h5>
                    <v-select :options="options"></v-select>
                </div>
            </b-col>
            <b-col md="10" sm="12">
                <div class="toolbar-sort clearfix">
                    <div class="showing-total">Showing 1-8 of 10 books</div>
                    <div class="group-sort">
                        <b-dropdown id="sort-sale" text="Sort by on sale" class="m-2">
                            <b-dropdown-item href="#">Sort by on sale</b-dropdown-item>
                            <b-dropdown-item href="#">Sort by on popularity</b-dropdown-item>
                            <b-dropdown-item href="#">Sort by price: low to high</b-dropdown-item>
                            <b-dropdown-item href="#">Sort by price: high to low</b-dropdown-item>
                        </b-dropdown>
                        <b-dropdown id="sort-records" text="Show 12" class="m-2">
                            <b-dropdown-item href="#">Show 6</b-dropdown-item>
                            <b-dropdown-item href="#">Show 12</b-dropdown-item>
                            <b-dropdown-item href="#">Show 24</b-dropdown-item>
                        </b-dropdown>
                    </div>
                </div>
                <b-row>
                    <b-col v-for="item in 12" :key="item" lg="4" md="6" xs="12">
                        <SingleBookCommon />
                    </b-col>
                </b-row>
                <b-row>
                  <b-col md="6" offset-md="3">
                    <b-pagination
                        v-model="currentPage"
                        total-rows="100"
                        :per-page="perPage"
                        first-text="First"
                        prev-text="Prev"
                        next-text="Next"
                        last-text="Last"
                      >
                      </b-pagination>
                  </b-col>
                </b-row>

            </b-col>
        </b-row>
    </div>
</template>
<script>
import SingleBookCommon from "@/components/SingleBookCommon.vue";

export default {

  name: 'Shop',
  components: {
    SingleBookCommon
  },
  data() {
    return {
      perPage: 10,
      currentPage: 1,
      options: [
        'foo',
        'bar',
        'baz'
      ]
    }
  }
}
</script>
<style lang="scss" scoped>
.shop-page {
  margin-top: 10px;

  .filter-item {
    margin: 15px 0;
    padding: 2px;
    text-align: left;

    .filter-title {
      font-weight: 700;
    }
  }

  .toolbar-sort {
    display: block;
    height: auto;
    width: 100%;
    padding: 20px 10px;

    .group-sort {
      display: inline-flex;
    }

    @media (min-width: 768px) {
      .showing-total {
        float: left;
      }

      .group-sort {
        float: right;
      }
    }
  }
}
</style>

// src/pages/Shop.jsx
import { Component, Fragment } from "react";
import PropTypes from 'prop-types';
import { Row, Col, Form, Dropdown, DropdownButton, Pagination } from 'react-bootstrap';
import images from '../assets/images/products/product3-250x250.jpg';
import SingleBookCommon from '../common/SingleBookCommon';
import ReactPaginate from 'react-paginate';
import Select from 'react-select'

const product = {
  imgSrc: images,
  title: 'Book Cartoon Tom&Jerry',
  price: '650.00'
};

const options = [
  { value: 'a', label: 'Book A' },
  { value: 'b', label: 'Book B' },
  { value: 'c', label: 'Book C' }
]

const FilterComponent = () => (
  <Select options={options} />
)

class Shop extends Component {

  renderProductsWithPaging = () => {
    let html = [];
    for (let i = 1; i <= 4; i++) {
      html.push(
        <Row key={i}>
          <Col lg={3} md={6} sm={12}><SingleBookCommon product={product}/></Col>
          <Col lg={3} md={6} sm={12}><SingleBookCommon product={product}/></Col>
          <Col lg={3} md={6} sm={12}><SingleBookCommon product={product}/></Col>
          <Col lg={3} md={6} sm={12}><SingleBookCommon product={product}/></Col>
        </Row>
      );
    }

    return html;
  }

  renderPagination = () => {
    return (
      <Pagination>
      <Pagination.Prev />
      <Pagination.Item>{1}</Pagination.Item>
      <Pagination.Item active>{2}</Pagination.Item>
      <Pagination.Item>{3}</Pagination.Item>
      <Pagination.Next />
    </Pagination>
    );
  }

  render() {
    let t = this.context.t

    return (
      <Fragment>
        <div className="shop-page">
          <Row>
            <Col lg={2} md={12}>
              <div className="sidebar-filter">
               <h4>Filter By</h4>
                <Form>
                  <Form.Group>
                    <Form.Label>Category</Form.Label>
                    <FilterComponent/>
                  </Form.Group>
                  <Form.Group>
                    <Form.Label>Author</Form.Label>
                    <FilterComponent/>
                  </Form.Group>
                  <Form.Group>
                    <Form.Label>Rating Review</Form.Label>
                    <Form.Control as="select">
                      <option>1 star</option>
                      <option>2 star</option>
                      <option>3 star</option>
                      <option>4 star</option>
                      <option>5 star</option>
                    </Form.Control>
                  </Form.Group>
                </Form>
              </div>
            </Col>
            <Col lg={10} md={12}>
              <div className="toolbar-sort clearfix">
                <div className="showing-total">Showing 1-12 of 100 books</div>
                <div className="group-sort">
                  <DropdownButton id="sort-sale" title="Sort by on sale" variant="secondary">
                    <Dropdown.Item href="#/action">Sort by on sale</Dropdown.Item>
                    <Dropdown.Item href="#/action">Sort by on popularity</Dropdown.Item>
                    <Dropdown.Item href="#/action">Sort by price: low to high</Dropdown.Item>
                    <Dropdown.Item href="#/action">Sort by price: high to low</Dropdown.Item>
                  </DropdownButton>
                  <DropdownButton id="sort-records" title="Show 20" variant="secondary">
                    <Dropdown.Item href="#/action">Show 20</Dropdown.Item>
                    <Dropdown.Item href="#/action">Show 50</Dropdown.Item>
                    <Dropdown.Item href="#/action">Show 100</Dropdown.Item>
                  </DropdownButton>
                </div>
              </div>
              
              {this.renderProductsWithPaging()}

              <Row>
                <Col md={{ span: 6, offset: 3 }}>
                  {this.renderPagination()}
                </Col>
              </Row>
            </Col>
          </Row>
        </div>
      </Fragment>
    );
  }

}

Shop.contextTypes = {
  t: PropTypes.func
}

export default Shop;
